node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /home/u1776723/mizab-api/server.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/server.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/u1776723/mizab-api/server.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.patch() requires a callback function but got a [object Undefined]
    at Route.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/route.js:211:15)
    at Function.proto.<computed> [as patch] (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/u1776723/mizab-api/routes/kalijaga_apps/auth.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/u1776723/mizab-api/app.js:10:20)
/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92
          throw new SequelizeErrors.ConnectionRefusedError(err);
                ^

ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
NOT OK ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:457:5) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
NOT OK ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:457:5) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
NOT OK ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:457:5) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
NOT OK ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:457:5) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
NOT OK ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:457:5) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
NOT OK ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/home/u1776723/nodevenv/mizab-api/16/lib/node_modules/sequelize/lib/sequelize.js:457:5) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}
